// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8JBb_5bxcjMcqsGlkoTZn5sFXqrhhWJY',
    appId: '1:627906800403:web:addf554adef3889caf08e6',
    messagingSenderId: '627906800403',
    projectId: 'zaki-app-4e55e',
    authDomain: 'zaki-app-4e55e.firebaseapp.com',
    storageBucket: 'zaki-app-4e55e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbyH3ukHFhG6Rge7JLne12wmIFvGU-38U',
    appId: '1:627906800403:android:a1f5e8f20edf90d1af08e6',
    messagingSenderId: '627906800403',
    projectId: 'zaki-app-4e55e',
    storageBucket: 'zaki-app-4e55e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAs3QQRzqJtM0__8QAvIaGSGoHxQ3onmQ',
    appId: '1:627906800403:ios:47034f0fef0f54d5af08e6',
    messagingSenderId: '627906800403',
    projectId: 'zaki-app-4e55e',
    storageBucket: 'zaki-app-4e55e.appspot.com',
    iosBundleId: 'com.example.feeeeeeee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAs3QQRzqJtM0__8QAvIaGSGoHxQ3onmQ',
    appId: '1:627906800403:ios:c04e601f2bcd0ea0af08e6',
    messagingSenderId: '627906800403',
    projectId: 'zaki-app-4e55e',
    storageBucket: 'zaki-app-4e55e.appspot.com',
    iosBundleId: 'com.example.feeeeeeee.RunnerTests',
  );
}
